### ISSUE TITLE
when i put slideSwitch in RelativeLayout,it can't show correctly

### ISSUE THREAD

**Issue by hncgc1990** [Leaking/SlideSwitch#3]
the problem is above in title

**Comment by hncgc1990** [comment]
is also show not correct in LinearLayout

**Comment by Leaking** [comment]
What happens when you see it doesn't  show correctly,,you mean it can't move?, can't show?
You can read the code in the TestLibs folder, I use the widget in linearlayout over there.

**Comment by hncgc1990** [comment]
sorry about that,i had found the problem.it is my tool's reason.it is weird about that i can show it correctly.Please forget about it.
