### ISSUE TITLE
Animation stops inside ScrollView

### ISSUE THREAD

**Issue by rafaelneiva** [Leaking/SlideSwitch#4]
Hi, thank you for sharing this widget, I really liked it.
I was using it and making some particular adaptations when I encountered an issue. If I use the widget inside a ScrollView, starting the move to any side and then moving down or up, the ScrollView intercepts the MotionEvent and the switch stops the animation in the middle.

I found a solution and I want to share with you. When ScrollView handle the event, its children Views triggers the MotionEvent ACTION_CANCEL. So I copied the code inside inside ACTION_UP (line 188) and added another case ACTION_CANCEL, like this:

```
       <rest of code> ...

            break;
        case MotionEvent.ACTION_MOVE:
            eventMovingY = (int) event.getY();
            diffY = eventMovingY - eventStartY;

            eventLastX = (int) event.getRawX();
            diffX = eventLastX - eventStartX;
            int tempX = diffX + frontRect_left_begin;
            tempX = (tempX > max_left ? max_left : tempX);
            tempX = (tempX < min_left ? min_left : tempX);
            if (tempX >= min_left && tempX <= max_left) {
                frontRect_left = tempX;
                alpha = (int) (255 * (float) tempX / (float) max_left);
                invalidateView();
            }

            break;
        case MotionEvent.ACTION_UP:
            moveToDest(isToRight(event));
            break;
        case MotionEvent.ACTION_CANCEL:
            moveToDest(isToRight(event));
            break;
        default:
            break;
    }

private boolean isToRight(MotionEvent event) {
    int wholeX = (int) (event.getRawX() - eventStartX);
    frontRect_left_begin = frontRect_left;
    boolean toRight;
    toRight = (frontRect_left_begin > max_left / 2 ? true : false);
    if (Math.abs(wholeX) < 3) {
        toRight = !toRight;
    }
    return toRight;
}
```

I'm sorry for my english and thank you again!

**Comment by Leaking** [comment]
Thx,
In the last version , i implements the animation by the Thread class, It performs bad.
Now i implement it by the ValueAnimation. It will perform better in various situtaions.

---My English is also poor. LOL

**Comment by rafaelneiva** [comment]
Yes, you're right about the animation. I tried the new code with ValueAnimator and looks so smooth now.
