### ISSUE TITLE
when i compile 'com.leaking.slideswitch:app:1.0.0', one issue occured

### ISSUE THREAD

**Issue by liaodalin19903** [Leaking/SlideSwitch#8]
Error:(34, 13)
 Failed to resolve: com.leaking.slideswitch:app:1.0.0

---

how can i resolve this issue?

**Comment by Leaking** [comment]
Sorry，I made some change to it but have not update the readme.
You can add the below codes in you module gradle file 

``` gradle
compile 'com.leaking.slideswitch:slideswitch:1.0.0'
```

And add the below codes in you project gradle file 

``` gradle
allprojects {
    repositories {
        jcenter()
        maven {
            url 'https://dl.bintray.com/leaking/maven'
        }
    }
}
```
